name: dog_telepathy
description: Dog emotion analysis app
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2
  
dependencies:
  animate_do: ^4.2.0
  camera: ^0.11.3
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  email_validator: ^3.0.0
  fl_chart: ^1.1.1
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.3+1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_webrtc: ^1.2.1
  gap: ^3.0.1
  go_router: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^3.0.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/onboarding/
